[tool.poetry]
name = "pyaoc-2022"
version = "1"
description = "Yearly AOC contest"
authors = ["Vasile-Hij <vasile.hijs@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "pyaoc_2022"}]

[tool.poetry.dependencies]
python = "^3.9"
ipdb = "^0.13.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
